# Generated by Django 5.1.4 on 2024-12-20 23:27

import django.db.models.deletion
import embed_video.fields
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.ImageField(default='amenities/default.png', upload_to='amenities/')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='associates/')),
            ],
        ),
        migrations.CreateModel(
            name='AwardsAndRecognitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='BlockedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='blogs/')),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BufferImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buffer_id', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='buffer/')),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='builders/')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='city/')),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventsAndCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(blank=True, max_length=20, null=True)),
                ('active_listing', models.CharField(blank=True, max_length=20, null=True)),
                ('worth_sold', models.CharField(blank=True, max_length=20, null=True)),
                ('happy_customers', models.CharField(blank=True, max_length=20, null=True)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('footer_about', models.TextField(blank=True, null=True)),
                ('featured', models.TextField(blank=True, null=True)),
                ('header_script', models.TextField(blank=True, null=True)),
                ('about_dream', models.TextField(blank=True, null=True)),
                ('about_nri', models.TextField(blank=True, null=True)),
                ('why_rera', models.TextField(blank=True, null=True)),
                ('why_deals', models.TextField(blank=True, null=True)),
                ('why_location', models.TextField(blank=True, null=True)),
                ('why_providing', models.TextField(blank=True, null=True)),
                ('disclaimer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('video_link', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('map_link', models.TextField(blank=True, null=True)),
                ('project_area', models.CharField(max_length=300)),
                ('project_type', models.CharField(max_length=300)),
                ('project_units', models.CharField(max_length=300)),
                ('project_buildup', models.CharField(max_length=300)),
                ('project_price', models.CharField(max_length=300)),
                ('project_status', models.CharField(max_length=300)),
                ('project_status_1', models.CharField(blank=True, max_length=300, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('master_plan', models.FileField(blank=True, null=True, upload_to='master_plan/')),
                ('master_plan_pdf', models.FileField(blank=True, null=True, upload_to='master_plan_pdf/')),
                ('location', models.TextField(blank=True, null=True)),
                ('rera_no', models.CharField(blank=True, max_length=300, null=True)),
                ('possession', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, max_length=300, null=True)),
                ('property_type_2', models.CharField(default='New Property', max_length=300)),
                ('bhk', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1 BHK', '1 BHK'), ('1.5 BHK', '1.5 BHK'), ('2 BHK', '2 BHK'), ('2.5 BHK', '2.5 BHK'), ('3 BHK', '3 BHK'), ('3.5 BHK', '3.5 BHK'), ('4 BHK', '4 BHK'), ('4+ BHK', '4+ BHK')], max_length=30, null=True)),
                ('location_direction', models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('Central', 'Central')], max_length=20, null=True)),
                ('cost', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('< 40L', '< 40L'), ('40L - 70L', '40L - 70L'), ('70L - 1Cr', '70L - 1Cr'), ('1Cr - 1.5Cr', '1Cr - 1.5Cr'), ('1Cr - 2Cr', '1Cr - 2Cr'), ('2Cr +', '2Cr +')], max_length=30, null=True)),
                ('property_id', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('builder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planet_app.builder')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planet_app.cities')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAdvantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('distance', models.CharField(blank=True, max_length=300, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet_app.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet_app.amenities')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet_app.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFloors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('tag1', models.CharField(blank=True, max_length=300, null=True)),
                ('tag2', models.CharField(blank=True, max_length=300, null=True)),
                ('tag3', models.CharField(blank=True, max_length=300, null=True)),
                ('tag4', models.CharField(blank=True, max_length=300, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='floors/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='floors/pdfs/')),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet_app.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='properties/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet_app.projectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(blank=True, max_length=300, null=True)),
                ('builtup', models.CharField(blank=True, max_length=300, null=True)),
                ('carpet', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.CharField(blank=True, max_length=300, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planet_app.projectdetails')),
            ],
        ),
    ]
