# Generated by Django 5.2.6 on 2025-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='project_currency',
            field=models.CharField(choices=[('usd', 'USD'), ('aed', 'AED'), ('inr', 'INR'), ('eur', 'EUR')], default='aed', max_length=10),
        ),
    ]
