# Generated by Django 5.2.6 on 2025-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_app', '0002_projectdetails_project_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFxRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(unique=True)),
                ('aed_to_usd', models.DecimalField(decimal_places=8, max_digits=18)),
                ('aed_to_eur', models.DecimalField(decimal_places=8, max_digits=18)),
                ('aed_to_inr', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of_date'],
            },
        ),
    ]
