# Generated by Django 5.2.6 on 2025-10-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_app', '0003_dailyfxrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='name_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='amenities',
            name='name_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='awardsandrecognitions',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardsandrecognitions',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardsandrecognitions',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='awardsandrecognitions',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ar',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='disclaimer_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='disclaimer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='name_ar',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='name_en',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='meta_keywords_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='meta_keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='meta_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='meta_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='name_ar',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cities',
            name='name_en',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='location_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='location_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='meta_keywords_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='meta_keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='meta_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='meta_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventsandcampaigns',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='keywords_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='location_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='location_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='meta_description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='meta_keywords_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='meta_keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='meta_title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='meta_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='possession_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='possession_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_area_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_area_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_buildup_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_buildup_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_price_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_price_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_status_1_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_status_1_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_status_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_status_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_type_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_type_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_units_ar',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='project_units_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='property_type_2_ar',
            field=models.CharField(default='New Property', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='property_type_2_en',
            field=models.CharField(default='New Property', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='property_type_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='property_type_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='title_ar',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='title_en',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertyadvantages',
            name='distance_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyadvantages',
            name='distance_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyadvantages',
            name='title_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyadvantages',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='name_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='name_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag1_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag1_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag2_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag2_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag3_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag3_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag4_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertyfloors',
            name='tag4_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='builtup_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='builtup_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='carpet_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='carpet_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='price_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='price_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='property_ar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='propertypricing',
            name='property_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='name_ar',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='name_en',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='designation_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='designation_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testimonial_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='testimonial_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='about_dream_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='about_dream_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='about_nri_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='about_nri_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='address_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='address_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='disclaimer_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='disclaimer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='featured_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='featured_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='footer_about_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='footer_about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_deals_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_deals_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_location_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_location_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_providing_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_providing_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_rera_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='why_rera_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
