# Generated by Django 5.0.6 on 2025-10-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_app', '0004_amenities_name_ar_amenities_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='brokers/')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('brn', models.CharField(blank=True, help_text='Broker Registration Number', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='dld_permit_number',
            field=models.CharField(blank=True, help_text='DLD Permit Number', max_length=300, null=True),
        ),
    ]
